export const storeProducts = [
  {
    id: 1,
    title: "Arya Stark",
    img: "images/product-1.png",
    price: 30,
    company: "HBO",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. ",
    inCart: false,
    inFavorites: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Goku Super Saiyan",
    img: "images/product-2.png",
    price: 20,
    company: "Toei Animation",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle.",
    inCart: false,
    inFavorites: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Alien - Covenant Movie",
    img: "images/product-3.png",
    price: 25,
    company: "20th Century Fox",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle.",
    inCart: false,
    inFavorites: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Darth Vader",
    img: "images/product-4.png",
    price: 28,
    company: "Walt Disney Pictures",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle.",
    inCart: false,
    inFavorites: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Dr. Strange",
    img: "images/product-5.png",
    price: 24,
    company: "Marvel Studios",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle.",
    inCart: false,
    inFavorites: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Black Panther",
    img: "images/product-6.png",
    price: 17,
    company: "Marvel Studios",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle.",
    inCart: false,
    inFavorites: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Dead Pool",
    img: "images/product-7.png",
    price: 30,
    company: "Marvel Studios",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle.",
    inCart: false,
    inFavorites: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Kratos and Atreus",
    img: "images/product-8.png",
    price: 32,
    company: "Santa Monica Studios",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle.",
    inCart: false,
    inFavorites: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Arya Stark",
  img: "images/product-1.png",
  price: 30,
  company: "HBO",
  info:
    "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle.",
  inCart: false,
  inFavorites: false,
  count: 0,
  total: 0,
};
